### ISSUE TITLE
联想延保签到失效

### ISSUE THREAD

**Issue by xygd555** [Wenmoux/checkbox#286]
【联想延保每日签到】：登陆成功！|| 获取token失败获取Cookie失败

**Comment by niko8868** [comment]
一样，试了几次之成功了一次
当前是青龙面板,路径：/ql
建议更新到最新版青龙再来运行哦,或者手动修改路径叭~
任务个数  1
------------开始签到任务------------
任务1执行中
任务开始
login：******
{
  lenovoid: *****,
  sessionid: '********',
  token: '**+oYsho*****RSl4***=='
}
{**
  status: 0,
  res: {
    success: true,
    continueCount: 1,
    yanbaoValue: 1,
    flashValue: false,
    flashCashVal: null,
    ledouValue: 20,
    scoreValue: 10,
    cashValue: false,
    couponValue: [],
    rewardTips: '获得1天延保\n20乐豆\n10积分\n1成长值',
    rewardSubTips: '',
    couponUrl: '',
    detailUrl: 'https://mclub.lenovo.com.cn/sign',
    growthValue: 1
  },
  time: 1692689575807
}
签到成功    获得1天延保
20乐豆
10积分
1成长值连续签到1天
------------任务执行完毕------------

【联想延保每日签到】：登陆成功！|| 签到成功||获得1天延保
20乐豆
10积分
1成长值 || 连续签到1天    


server酱发送通知消息成功🎉

push+发送一对一通知消息完成。

telegram发送通知消息失败！！

RequestError: Timeout awaiting 'request' for 15000ms
    at ClientRequest.<anonymous> (/ql/data/scripts/node_modules/.pnpm/got@11.5.1/node_modules/got/dist/source/core/index.js:887:25)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at origin.emit (/ql/data/scripts/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (/ql/data/scripts/node_modules/.pnpm/got@11.5.1/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:571:11)
    at process.processTimers (node:internal/timers:512:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1692689576849,
    socket: 1692689576852,
    lookup: 1692689576866,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1692689591855,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 14,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 15006
    }
  },
  event: 'request'
}
