### ISSUE TITLE
书客阅读自动签到崩了

### ISSUE THREAD

**Issue by haicao8848** [Wenmoux/checkbox#344]
书客（刺猬猫）阅读自动签到脚本（hbooker）崩了会报错：
{ code: '320002', tip: '网络出错，请重试或重新登录' }
TypeError: Cannot read properties of undefined (reading 'prop_info')
    at /ql/data/scripts/Wenmoux_checkbox_master/scripts/hbooker.js:155:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async give (/ql/data/scripts/Wenmoux_checkbox_master/scripts/hbooker.js:149:16)
    at async hbooker (/ql/data/scripts/Wenmoux_checkbox_master/scripts/hbooker.js:406:9)
    at async /ql/data/scripts/Wenmoux_checkbox_master/checkbox.js:53:34
已经试过了，不是账号问题，而且抓包时发现了多了一串数值p=xxxxx的

**Comment by hhtnFxQVwQntBLkULKjy** [comment]
一样
